USE [master]
GO

/****** Object:  Database [SCA]    Script Date: 09/04/2020 22:56:18 ******/
CREATE DATABASE [SCA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SCA', FILENAME = N'C:\Users\Osvaldo Junior\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\SCA.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SCA_log', FILENAME = N'C:\Users\Osvaldo Junior\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\SCA.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SCA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SCA] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [SCA] SET ANSI_NULLS ON 
GO

ALTER DATABASE [SCA] SET ANSI_PADDING ON 
GO

ALTER DATABASE [SCA] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [SCA] SET ARITHABORT ON 
GO

ALTER DATABASE [SCA] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SCA] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [SCA] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SCA] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SCA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SCA] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [SCA] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [SCA] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SCA] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [SCA] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SCA] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SCA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SCA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SCA] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SCA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SCA] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SCA] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SCA] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SCA] SET RECOVERY FULL 
GO

ALTER DATABASE [SCA] SET  MULTI_USER 
GO

ALTER DATABASE [SCA] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SCA] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SCA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SCA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SCA] SET  READ_WRITE 
GO


